#%%
import astropy.units as u

path_map = '/home/pablo/Desktop/Paper/maps/'
path_masks = '/home/pablo/Desktop/Paper/masks/'

data = {
    'QUIJOTE': {
        '11': {
            'freq': 11.1 * u.GHz,
            'fwhm': 55.38 * u.arcmin,
            'noise_I': 3.481 * u.mK,
            'noise_QU': 1.372 * u.mK,
            'path': path_map + 'QUIJOTE/quijote_mfi_skymap_11ghz_512_dr1.fits',
            'path_simulated': path_map + 'PYSM/QUIJOTE_11GHz_n512_fwhm_5538.fits',
            'beam': path_map + 'QUIJOTE/beam/rimo_quijote_mfi_beamtf_dr1.fits',
            'hmdm': path_map + 'QUIJOTE/hmdm/quijote_311_HMDM.fits',
            'half_1': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_11ghz_512_dr1_half1.fits',
            'half_2': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_11ghz_512_dr1_half2.fits',
            'path_noise_simulations': path_map + 'QUIJOTE/noise_simulations/11_quijote/',
            'path_white_noise_simulations': path_map + 'QUIJOTE/noise_simulations/11/',
            'noise_simulation_1': 'quijote_11GHz_horn3_0001_sm1deg.fits',
            'white_noise_simulation_1': 'white_noise_11ghz_0001.fits',
        },
        '13': {
            'freq': 12.9 * u.GHz,
            'fwhm': 55.84 * u.arcmin,
            'noise_I': 2.422 * u.mK,
            'noise_QU': 1.188 * u.mK,
            'path': path_map + 'QUIJOTE/quijote_mfi_skymap_13ghz_512_dr1.fits',
            'path_simulated': path_map + 'PYSM/QUIJOTE_13GHz_n512_fwhm_5584.fits',
            'beam': path_map + 'QUIJOTE/beam/rimo_quijote_mfi_beamtf_dr1.fits',
            'hmdm': path_map + 'QUIJOTE/hmdm/quijote_313_HMDM.fits',
            'half_1': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_13ghz_512_dr1_half1.fits',
            'half_2': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_13ghz_512_dr1_half2.fits',
            'path_noise_simulations': path_map + 'QUIJOTE/noise_simulations/13_quijote/',
            'path_white_noise_simulations': path_map + 'QUIJOTE/noise_simulations/13/',
            'noise_simulation_1': 'quijote_13GHz_horn3_0001_sm1deg.fits',
            'white_noise_simulation_1': 'white_noise_13ghz_0001.fits',
        },
        '17': {
            'freq': 16.8 * u.GHz,
            'fwhm': 38.95 * u.arcmin,
            'noise_I':  7.939 * u.mK,
            'noise_QU': 1.101 * u.mK,
            'path': path_map + 'QUIJOTE/quijote_mfi_skymap_17ghz_512_dr1.fits',
            'path_simulated': path_map + 'PYSM/QUIJOTE_17GHz_n512_fwhm_3895.fits',
            'beam': path_map + 'QUIJOTE/beam/rimo_quijote_mfi_beamtf_dr1.fits',
            'hmdm': path_map + 'QUIJOTE/hmdm/quijote_417_HMDM.fits',
            'half_1': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_17ghz_512_dr1_half1.fits',
            'half_2': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_17ghz_512_dr1_half2.fits',
            'path_noise_simulations': path_map + 'QUIJOTE/noise_simulations/17_quijote/',
            'path_white_noise_simulations': path_map + 'QUIJOTE/noise_simulations/17/',
            'noise_simulation_1': 'quijote_17GHz_horn4_0001_sm1deg.fits',
            'white_noise_simulation_1': 'white_noise_17ghz_0001.fits',
        },
        '19': {
            'freq': 18.8 * u.GHz,
            'fwhm': 40.32 * u.arcmin,
            'noise_I': 8.427 * u.mK,
            'noise_QU':  1.064 * u.mK,
            'path': path_map + 'QUIJOTE/quijote_mfi_skymap_19ghz_512_dr1.fits',
            'path_simulated': path_map + 'PYSM/QUIJOTE_19GHz_n512_fwhm_4032.fits',
            'beam': path_map + 'QUIJOTE/beam/rimo_quijote_mfi_beamtf_dr1.fits',
            'hmdm': path_map + 'QUIJOTE/hmdm/quijote_419_HMDM.fits',
            'half_1': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_19ghz_512_dr1_half1.fits',
            'half_2': path_map + 'QUIJOTE/hmdm/quijote_mfi_skymap_19ghz_512_dr1_half2.fits',
            'path_noise_simulations': path_map + 'QUIJOTE/noise_simulations/19_quijote/',
            'path_white_noise_simulations': path_map + 'QUIJOTE/noise_simulations/19/',
            'noise_simulation_1': 'quijote_19GHz_horn4_0001_sm1deg.fits',
            'white_noise_simulation_1': 'white_noise_19ghz_0001.fits',
        },
    },
    'WMAP': {
        '23': {
            'freq': 22.72 * u.GHz,
            'fwhm': 52.8 * u.arcmin,
            'noise_I': 1.429 * u.mK,      
            'noise_QU': 1.435 * u.mK,
            'path': path_map + 'WMAP/wmap_band_iqumap_r9_9yr_K_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_23GHz_n512_fwhm_5280.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_K_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/wmap_iqumap_r9_yr1to4_K_v5.fits',
            'half_2': path_map + 'WMAP/hmdm/wmap_iqumap_r9_yr5to9_K_v5.fits',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/23/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/23/',
            'noise_simulation_1': 'white_noise_23ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_23ghz_0001.fits',
        },
        '33': {
            'freq': 32.98 * u.GHz,
            'fwhm': 39.6 * u.arcmin,
            'noise_I': 1.466 * u.mK,
            'noise_QU': 1.472 * u.mK,
            'path': path_map + 'WMAP/wmap_band_iqumap_r9_9yr_Ka_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_33GHz_n512_fwhm_3960.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_Ka_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/33/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/33/',
            'noise_simulation_1': 'white_noise_33ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_33ghz_0001.fits',
        },
        '41': {
            'freq': 40.77 * u.GHz,
            'fwhm': 30.6 * u.arcmin,
            'noise_I': 2.188 * u.mK,
            'noise_QU': 2.197 * u.mK,
            'path': path_map + 'WMAP/wmap_band_iqumap_r9_9yr_Q_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_41GHz_n512_fwhm_3060.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_Q_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/41/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/41/',
            'noise_simulation_1': 'white_noise_41ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_41ghz_0001.fits',
        },
        '61': {
            'freq': 60.12 * u.GHz,
            'fwhm': 21.0 * u.arcmin,
            'noise_I': 3.131 * u.mK,
            'noise_QU': 3.141 * u.mK,
            'path': path_map + 'WMAP/wmap_band_iqumap_r9_9yr_V_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_61GHz_n512_fwhm_2100.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_V_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/61/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/61/',
            'noise_simulation_1': 'white_noise_61ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_61ghz_0001.fits',
        },
        '94': {
            'freq': 92.87 * u.GHz,
            'fwhm': 13.2 * u.arcmin,
            'noise_I': 6.544 * u.mK,
            'noise_QU': 6.560 * u.mK,
            'path': path_map + 'WMAP/wmap_band_iqumap_r9_9yr_W_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_94GHz_n512_fwhm_1320.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_W_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/94/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/94/',
            'noise_simulation_1': 'white_noise_94ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_94ghz_0001.fits',
        },

        '23_1': {
            'freq': 22.72 * u.GHz,
            'fwhm': 52.8 * u.arcmin,
            'noise_I': 1.437 * u.mK,      
            'noise_QU': 1.456 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_K1_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_23_1GHz_n512_fwhm_5280.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_K1_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/wmap_iqumap_r9_yr1to4_K_v5.fits',
            'half_2': path_map + 'WMAP/hmdm/wmap_iqumap_r9_yr5to9_K_v5.fits',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/23_1/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/23_1/',
            'noise_simulation_1': 'white_noise_23_1ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_23_1ghz_0001.fits',
        },
        '33_1': {
            'freq': 32.98 * u.GHz,
            'fwhm': 39.6 * u.arcmin,
            'noise_I': 1.470 * u.mK,
            'noise_QU': 1.490 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_Ka1_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_33_1GHz_n512_fwhm_3960.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_Ka1_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/33_1/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/33_1/',
            'noise_simulation_1': 'white_noise_33_1ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_33_1ghz_0001.fits',
        },
        '41_1': {
            'freq': 40.77 * u.GHz,
            'fwhm': 30.6 * u.arcmin,
            'noise_I': 2.254 * u.mK,
            'noise_QU': 2.280 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_Q1_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_41_1GHz_n512_fwhm_3060.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_Q1_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/41_1/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/41_1/',
            'noise_simulation_1': 'white_noise_41_1ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_41_1ghz_0001.fits',
        },
        '41_2': {
            'freq': 40.56 * u.GHz,
            'fwhm': 30.6 * u.arcmin,
            'noise_I': 2.140 * u.mK,
            'noise_QU': 2.164 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_Q2_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_41_2GHz_n512_fwhm_3060.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_Q2_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/41_2/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/41_2/',
            'noise_simulation_1': 'white_noise_41_2ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_41_2ghz_0001.fits',
        },
        '61_1': {
            'freq': 60.12 * u.GHz,
            'fwhm': 21.0 * u.arcmin,
            'noise_I': 3.319 * u.mK,
            'noise_QU': 3.348 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_V1_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_61_1GHz_n512_fwhm_2100.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_V1_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/61_1/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/61_1/',
            'noise_simulation_1': 'white_noise_61_1ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_61_1ghz_0001.fits',
        },
        '61_2': {
            'freq': 60.00 * u.GHz,
            'fwhm': 21.0 * u.arcmin,
            'noise_I': 2.955 * u.mK,
            'noise_QU': 2.979 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_V2_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_61_2GHz_n512_fwhm_2100.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_V2_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/61_2/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/61_2/',
            'noise_simulation_1': 'white_noise_61_2ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_61_2ghz_0001.fits',
        },
        '94_1': {
            'freq': 92.87 * u.GHz,
            'fwhm': 13.2 * u.arcmin,
            'noise_I': 5.906 * u.mK,
            'noise_QU': 5.940 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_W1_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_94_1GHz_n512_fwhm_1320.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_W1_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/94_1/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/94_1/',
            'noise_simulation_1': 'white_noise_94_1ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_94_1ghz_0001.fits',
        },
        '94_2': {
            'freq': 93.43 * u.GHz,
            'fwhm': 13.2 * u.arcmin,
            'noise_I': 6.572 * u.mK,
            'noise_QU': 6.612 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_W2_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_94_2GHz_n512_fwhm_1320.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_W2_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/94_2/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/94_2/',
            'noise_simulation_1': 'white_noise_94_2ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_94_2ghz_0001.fits',
        },
        '94_3': {
            'freq': 92.44 * u.GHz,
            'fwhm': 13.2 * u.arcmin,
            'noise_I': 6.941 * u.mK,
            'noise_QU': 6.983 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_W3_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_94_3GHz_n512_fwhm_1320.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_W3_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/94_3/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/94_3/',
            'noise_simulation_1': 'white_noise_94_3ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_94_3ghz_0001.fits',
        },
        '94_4': {
            'freq': 93.22 * u.GHz,
            'fwhm': 13.2 * u.arcmin,
            'noise_I': 6.778 * u.mK,
            'noise_QU': 6.840 * u.mK,
            'path': path_map + 'WMAP/wmap_iqumap_r9_9yr_W4_v5.fits',
            'path_simulated': path_map + 'PYSM/WMAP_94_4GHz_n512_fwhm_1320.fits',
            'beam': path_map + 'WMAP/beam/wmap_ampl_bl_W4_9yr_v5p1.txt',
            'hmdm': path_map + 'WMAP/hmdm/',
            'half_1': path_map + 'WMAP/hmdm/',
            'half_2': path_map + 'WMAP/hmdm/',
            'path_noise_simulations': path_map + 'WMAP/noise_simulations/94_4/',
            'path_white_noise_simulations': path_map + 'WMAP/noise_simulations/94_4/',
            'noise_simulation_1': 'white_noise_94_4ghz_0001.fits',
            'white_noise_simulation_1': 'white_noise_94_4ghz_0001.fits',
        },
    },
    'Planck': {
        '30': {
            'freq': 28.4 * u.GHz,
            'fwhm': 32.29 * u.arcmin,
            'noise_I': 2.5e-6 * u.K,
            'noise_QU': 3.5e-6 * u.K,
            'path': path_map + 'Planck/LFI_SkyMap_030-BPassCorrected_1024_R3.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_30GHz_n512_fwhm_3229.fits',
            'beam': path_map + 'Planck/beam/LFI_RIMO_R3.31.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/LFI_SkyMap_030-BPassCorrected_1024_R3.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/LFI_SkyMap_030-BPassCorrected_1024_R3.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/30_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/30/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_30ghz_0001.fits',
        },
        '44': {
            'freq': 44.1 * u.GHz,
            'fwhm': 26.99 * u.arcmin,
            'noise_I': 2.7e-6 * u.K,
            'noise_QU': 4.0e-6 * u.K,
            'path': path_map + 'Planck/LFI_SkyMap_044-BPassCorrected_1024_R3.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_44GHz_n512_fwhm_2699.fits',
            'beam': path_map + 'Planck/beam/LFI_RIMO_R3.31.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/LFI_SkyMap_044-BPassCorrected_1024_R3.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/LFI_SkyMap_044-BPassCorrected_1024_R3.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/44_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/44/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_44ghz_0001.fits',
        },
        '70': {
            'freq': 70.4 * u.GHz,
            'fwhm': 13.22 * u.arcmin,
            'noise_I': 3.5e-6 * u.K,
            'noise_QU': 5.0e-6 * u.K,
            'path': path_map + 'Planck/LFI_SkyMap_070-BPassCorrected_1024_R3.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_70GHz_n512_fwhm_1322.fits',
            'beam': path_map + 'Planck/beam/LFI_RIMO_R3.31.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/LFI_SkyMap_070-BPassCorrected_1024_R3.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/LFI_SkyMap_070-BPassCorrected_1024_R3.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/70_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/70/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_70ghz_0001.fits',
        },
        '100': {
            'freq': 101.31 * u.GHz,
            'fwhm': 9.680 * u.arcmin,
            'noise_I': 1.29e-6 * u.K,
            'noise_QU': 1.96e-6 * u.K,  
            'path': path_map + 'Planck/HFI_SkyMap_100_2048_R3.01_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_100GHz_n512_fwhm_0968.fits',
            'beam': path_map + 'Planck/beam/Bl_TEB_R3.01_fullsky_100x100.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_100-BPassCorrected_2048_R3.01_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_100-BPassCorrected_2048_R3.01_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/100_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/100/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_100ghz_0001.fits',
        },
        '143': {
            'freq': 142.709 * u.GHz,
            'fwhm': 7.300 * u.arcmin,
            'noise_I': 0.55e-6 * u.K,
            'noise_QU': 1.17e-6 * u.K,
            'path': path_map + 'Planck/HFI_SkyMap_143_2048_R3.01_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_143GHz_n512_fwhm_0730.fits',
            'beam': path_map + 'Planck/beam/Bl_TEB_R3.01_fullsky_143x143.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_143-BPassCorrected_2048_R3.01_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_143-BPassCorrected_2048_R3.01_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/143_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/143/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_143ghz_0001.fits',
        },
        '217': {
            'freq': 221.914 * u.GHz,
            'fwhm': 5.020 * u.arcmin,
            'noise_I': 0.78e-6 * u.K,
            'noise_QU': 1.75e-6 * u.K,
            'path': path_map + 'Planck/HFI_SkyMap_217_2048_R3.01_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_217GHz_n512_fwhm_0502.fits',
            'beam': path_map + 'Planck/beam/Bl_TEB_R3.01_fullsky_217x217.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_217-BPassCorrected_2048_R3.01_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_217-BPassCorrected_2048_R3.01_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/217_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/217/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_217ghz_0001.fits',
        },
        '353': {
            'freq': 361.289 * u.GHz,
            'fwhm': 4.940 * u.arcmin,
            'noise_I': 2.56e-6 * u.K,
            'noise_QU': 7.31e-6 * u.K,
            'path': path_map + 'Planck/HFI_SkyMap_353-psb_2048_R3.01_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_353GHz_n512_fwhm_0494.fits',
            'beam': path_map + 'Planck/beam/Bl_TEB_R3.01_fullsky_353x353.fits',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_353-BPassCorrected_2048_R3.01_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_353-BPassCorrected_2048_R3.01_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/353_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/353/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_353ghz_0001.fits',
        },

        '30_pr4': {
            'freq': 28.4 * u.GHz,
            'fwhm': 32.29 * u.arcmin,
            'noise_I': 2.5e-6 * u.K,
            'noise_QU': 3.5e-6 * u.K,
            'path': path_map + 'Planck/LFI_SkyMap_030-BPassCorrected_1024_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_30_pr4GHz_n512_fwhm_3229.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/planck_PR4_030_HMDM.fits',
            'half_1': path_map + 'Planck/hmdm/LFI_SkyMap_030-BPassCorrected_1024_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/LFI_SkyMap_030-BPassCorrected_1024_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/30_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/30_pr4/',
            'noise_simulation_1': 'npipe6v20_noise_030_mc_00200.fits',
            'white_noise_simulation_1': 'white_noise_30_pr4ghz_0001.fits',
        },
        '44_pr4': {
            'freq': 44.1 * u.GHz,
            'fwhm': 26.99 * u.arcmin,
            'noise_I': 2.7e-6 * u.K,
            'noise_QU': 4.0e-6 * u.K,
            'path': path_map + 'Planck/LFI_SkyMap_044-BPassCorrected_1024_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_44_pr4GHz_n512_fwhm_2699.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/LFI_SkyMap_044-BPassCorrected_1024_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/LFI_SkyMap_044-BPassCorrected_1024_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/44_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/44_pr4/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_44_pr4ghz_0001.fits',
        },
        '70_pr4': {
            'freq': 70.4 * u.GHz,
            'fwhm': 13.22 * u.arcmin,
            'noise_I': 3.5e-6 * u.K,
            'noise_QU': 5.0e-6 * u.K,
            'path': path_map + 'Planck/LFI_SkyMap_070-BPassCorrected_1024_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_70_pr4GHz_n512_fwhm_1322.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/LFI_SkyMap_070-BPassCorrected_1024_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/LFI_SkyMap_070-BPassCorrected_1024_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/70_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/70_pr4/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_70_pr4ghz_0001.fits',
        },
        '100_pr4': {
            'freq': 101.31 * u.GHz,
            'fwhm': 9.680 * u.arcmin,
            'noise_I': 1.29e-6 * u.K,
            'noise_QU': 1.96e-6 * u.K,  
            'path': path_map + 'Planck/HFI_SkyMap_100-BPassCorrected_2048_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_100_pr4GHz_n512_fwhm_0968.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_100-BPassCorrected_2048_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_100-BPassCorrected_2048_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/100_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/100_pr4/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_100_pr4ghz_0001.fits',
        },
        '143_pr4': {
            'freq': 142.709 * u.GHz,
            'fwhm': 7.300 * u.arcmin,
            'noise_I': 0.55e-6 * u.K,
            'noise_QU': 1.17e-6 * u.K,
            'path': path_map + 'Planck/HFI_SkyMap_143-BPassCorrected_2048_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_143_pr4GHz_n512_fwhm_0730.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_143-BPassCorrected_2048_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_143-BPassCorrected_2048_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/143_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/143_pr4/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_143_pr4ghz_0001.fits',
        },
        '217_pr4': {
            'freq': 221.914 * u.GHz,
            'fwhm': 5.020 * u.arcmin,
            'noise_I': 0.78e-6 * u.K,
            'noise_QU': 1.75e-6 * u.K,
            'path': path_map + 'Planck/HFI_SkyMap_217-BPassCorrected_2048_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_217_pr4GHz_n512_fwhm_0502.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_217-BPassCorrected_2048_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_217-BPassCorrected_2048_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/217_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/217_pr4/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_217_pr4ghz_0001.fits',
        },
        '353_pr4': {
            'freq': 361.289 * u.GHz,
            'fwhm': 4.940 * u.arcmin,
            'noise_I': 2.56e-6 * u.K,
            'noise_QU': 7.31e-6 * u.K,
            'path': path_map + 'Planck/HFI_SkyMap_353-BPassCorrected_2048_R4.00_full.fits',
            'path_simulated': path_map + 'PYSM/Planck_353_pr4GHz_n512_fwhm_0494.fits',
            'beam': path_map + 'Planck/beam/',
            'hmdm': path_map + 'Planck/hmdm/',
            'half_1': path_map + 'Planck/hmdm/HFI_SkyMap_353-BPassCorrected_2048_R4.00_full-ringhalf-1.fits',
            'half_2': path_map + 'Planck/hmdm/HFI_SkyMap_353-BPassCorrected_2048_R4.00_full-ringhalf-2.fits',
            'path_noise_simulations': path_map + 'Planck/noise_simulations/353_pr4_pla/',
            'path_white_noise_simulations': path_map + 'Planck/noise_simulations/353_pr4/',
            'noise_simulation_1': '',
            'white_noise_simulation_1': 'white_noise_353_pr4ghz_0001.fits',
        },
    }
}


masks = {
    'quijote': {
        'lowdec_satband': {
            'name': 'quijote',
            'fsky': 0.,
            'path': path_masks + 'quijote/mask_quijote_ncp_lowdec_satband_nside512.fits'
        },
        'satband': {
            'name': 'quijote_satband',
            'fsky': 0.,
            'path': path_masks + 'quijote/mask_quijote_satband_ncp86_nside512.fits'
        },
    },

    'quijote_galcut': {
        'galcut5': {
            'name': 'quijote_galcut5',
            'fsky': 0.38,
            'path': path_masks + 'quijote_galcut/mask_galcut5_dec_6_70_apodC2_5.fits'
        },
        'galcut10': {
            'name': 'quijote_galcut10',
            'fsky': 0.34,
            'path': path_masks + 'quijote_galcut/mask_galcut10_dec_6_70_apodC2_5.fits'
        },
        'galcut20': {
            'name': 'quijote_galcut20',
            'fsky': 0.27,
            'path': path_masks + 'quijote_galcut/mask_galcut20_dec_6_70_apodC2_5.fits'
        },
    },

    'north_south': {
        'north': {
            'name': 'quijote_north',
            'fsky': 0.,
            'path': path_masks + 'north_south/mask_north_dec_6_70_apodC2_5_pc.fits'
        },
        'south': {
            'name': 'quijote_south',
            'fsky': 0.,
            'path': path_masks + 'north_south/mask_south_dec_6_70_apodC2_5_pc.fits'
        },
    },

    'specific_regions': {
        '140_0_r30': {
            'name': 'quijote_140_0_r30',
            'fsky': 0.,
            'path': path_masks + 'specific_regions/'
        },
        '65_0_r30': {
            'name': 'quijote_65_0_r30',
            'fsky': 0.,
            'path': path_masks + 'specific_regions/'
        },
        '37_40_r35': {
            'name': 'quijote_37_40_r35',
            'fsky': 0.,
            'path': path_masks + 'specific_regions/'
        },
        '117_50_r40': {
            'name': 'quijote_117_50_r40',
            'fsky': 0.,
            'path': path_masks + 'specific_regions/'
        },
        '150_45_r45': {
            'name': 'quijote_150_45_r30',
            'fsky': 0.,
            'path': path_masks + 'specific_regions/'
        },
    },
    
}